package render

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"strings"
	"time"

	"github.com/GrantPukka/loupe/internal/session"
)

// HandoffFormat is how an extract is written.
type HandoffFormat string

const (
	// HandoffMarkdown is the default: pasteable into a ticket.
	HandoffMarkdown HandoffFormat = "md"
	HandoffJSON     HandoffFormat = "json"
	// HandoffZip bundles the markdown, the JSON, and the raw lines.
	HandoffZip HandoffFormat = "zip"
)

// HandoffFormatFor picks the format from a filename's extension.
//
// docs/HANDOFF.md section 1: formats by extension. Writing to a dash means
// stdout, which is markdown so it can be piped straight to a clipboard.
func HandoffFormatFor(path string) (HandoffFormat, error) {
	if path == "-" {
		return HandoffMarkdown, nil
	}

	switch strings.ToLower(filepath.Ext(path)) {
	case ".md", ".markdown", "":
		return HandoffMarkdown, nil
	case ".json":
		return HandoffJSON, nil
	case ".zip":
		return HandoffZip, nil
	default:
		return "", fmt.Errorf("cannot tell the handoff format from %q: "+
			"use .md, .json, or .zip", filepath.Base(path))
	}
}

// WriteHandoff renders an extract.
func WriteHandoff(w io.Writer, h session.Handoff, format HandoffFormat) error {
	switch format {
	case HandoffJSON:
		return writeHandoffJSON(w, h)
	case HandoffZip:
		return writeHandoffZip(w, h)
	default:
		return writeHandoffMarkdown(w, h)
	}
}

func writeHandoffJSON(w io.Writer, h session.Handoff) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	if err := enc.Encode(h); err != nil {
		return fmt.Errorf("write handoff json: %w", err)
	}
	return nil
}

// writeHandoffMarkdown renders the shape in docs/HANDOFF.md section 3.
//
// Ordered by what the receiving engineer reads first: the window, the query,
// the counts, the sources and their timezone provenance, the records, and the
// raw lines. Assumptions and exclusions appear whether or not they are
// interesting, because silence about them is how a handoff misleads.
func writeHandoffMarkdown(w io.Writer, h session.Handoff) error {
	var b strings.Builder

	b.WriteString("# Log extract\n\n")

	if h.WindowLocal != "" {
		fmt.Fprintf(&b, "**Window**   %s  \n", h.WindowLocal)
		fmt.Fprintf(&b, "             %s\n", h.WindowUTC)
	} else {
		fmt.Fprintf(&b, "**Window**   all time (no time filter)\n")
	}

	fmt.Fprintf(&b, "**Timezone** %s — times below are shown in it, with a UTC column\n", h.Timezone)

	if h.Query != "" {
		fmt.Fprintf(&b, "**Query**    `%s`\n", h.Query)
	} else {
		fmt.Fprintf(&b, "**Query**    (none — every record)\n")
	}

	fmt.Fprintf(&b, "**Matched**  %s records of %s ingested\n",
		Commas(h.Counts.Matched), Commas(h.Counts.Ingested))

	// Every exclusion is stated. A reader who is not told data was left out
	// cannot know to ask.
	if h.Counts.ExcludedNoTimestamp > 0 {
		fmt.Fprintf(&b, "**Excluded** %s records had no parseable timestamp, so the time filter could not include them (`ts:none` finds them)\n",
			Commas(h.Counts.ExcludedNoTimestamp))
	}
	if h.Counts.Unparsed > 0 {
		fmt.Fprintf(&b, "**Unparsed** %s lines matched no parser; their raw text is kept and searchable\n",
			Commas(h.Counts.Unparsed))
	}
	if h.Truncated {
		fmt.Fprintf(&b, "**Truncated** showing the first %s of %s matched records — re-run with `--limit` for the rest\n",
			Commas(h.Counts.Shown), Commas(h.Counts.Matched))
	}
	if len(h.Redacted) > 0 {
		fmt.Fprintf(&b, "**Redacted** %s — values replaced with a stable hash, so records still correlate\n",
			strings.Join(h.Redacted, ", "))
	}

	for _, note := range h.Notes {
		fmt.Fprintf(&b, "**Note**     %s\n", note)
	}

	writeHandoffSources(&b, h)
	writeHandoffTrace(&b, h)
	writeHandoffRecords(&b, h)
	writeHandoffRaw(&b, h)

	fmt.Fprintf(&b, "\n---\nGenerated by %s %s on %s by %s at %s\n",
		h.Meta.Tool, h.Meta.Version, h.Meta.Host, h.Meta.User,
		h.Meta.At.Format(time.RFC3339))
	if h.Meta.Command != "" {
		fmt.Fprintf(&b, "`%s`\n", h.Meta.Command)
	}

	_, err := io.WriteString(w, b.String())
	return err
}

// writeHandoffTrace renders one request's path, when the extract is about one.
//
// Above the record table, because the order and the waits are the finding and
// the records below are the evidence for it. What could not be checked is
// printed with it: a receiver cannot see the absence of a source that was never
// able to answer in the first place.
func writeHandoffTrace(b *strings.Builder, h session.Handoff) {
	t := h.Trace
	if t == nil {
		return
	}

	fmt.Fprintf(b, "\n## Trace %s\n\n", t.ID)
	fmt.Fprintf(b, "Followed on `%s`", t.Field)
	if t.Span != "" {
		fmt.Fprintf(b, ", spanning %s", t.Span)
	}
	b.WriteString(".\n\n")

	b.WriteString("| Time | UTC | Wait | Source | Level | Message |\n")
	b.WriteString("|---|---|---|---|---|---|\n")

	for _, hop := range t.Hops {
		local, utc := hop.Local, hop.UTC
		if local == "" {
			// Stated, not blank. A blank cell reads as a rendering fault,
			// where "no timestamp" is a fact about the record.
			local, utc = "no timestamp", "—"
		}

		wait := hop.Gap
		if wait != "" {
			wait = "+" + wait
			if hop.Slowest {
				wait += " ◀"
			}
		}

		fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %s |\n",
			local, utc, wait, markdownCell(hop.Source), hop.Level,
			markdownCell(firstLine(hop.Message)))
	}

	if t.Undated > 0 {
		fmt.Fprintf(b, "\n**Undated**  %d hop(s) carry no timestamp and are listed last, "+
			"in ingest order.\n", t.Undated)
	}
	if len(t.Blind) > 0 {
		fmt.Fprintf(b, "\n**Not checked** %s never record `%s`, so this trace cannot say "+
			"whether the request reached them.\n", strings.Join(t.Blind, ", "), t.Field)
	}
	if len(t.Silent) > 0 {
		fmt.Fprintf(b, "\n**Silent** %s record `%s` but none for this id.\n",
			strings.Join(t.Silent, ", "), t.Field)
	}
}

func writeHandoffSources(b *strings.Builder, h session.Handoff) {
	if len(h.Sources) == 0 {
		return
	}

	b.WriteString("\n## Sources\n\n")
	b.WriteString("| File | Format | Size | Records | Timezone |\n")
	b.WriteString("|---|---|---|---|---|\n")

	for _, s := range h.Sources {
		// An assumed timezone is emphasised. A receiver who does not know an
		// assumption was made cannot check it.
		zone := s.Timezone
		if !strings.HasPrefix(zone, "known") {
			zone = "**" + zone + "**"
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n",
			s.File, s.Format, humanBytes(s.Bytes), Commas(s.Records), zone)
	}

	if assumed := h.AssumedSources(); len(assumed) > 0 {
		names := make([]string, len(assumed))
		for i, s := range assumed {
			names[i] = filepath.Base(s.File)
		}
		fmt.Fprintf(b, "\n> The timezone for %s was assumed, not read from the format. "+
			"If those servers do not run UTC, their timestamps above are offset by the difference.\n",
			strings.Join(names, ", "))
	}
}

func writeHandoffRecords(b *strings.Builder, h session.Handoff) {
	if len(h.Records) == 0 {
		b.WriteString("\n## Records\n\nNo records matched.\n")
		return
	}

	b.WriteString("\n## Records\n\n")
	fmt.Fprintf(b, "| Time (%s) | Time (UTC) | Level | Source | Message |\n", h.Timezone)
	b.WriteString("|---|---|---|---|---|\n")

	for _, r := range h.Records {
		local, utc := r.Local, r.UTC
		if local == "" {
			local, utc = "*none*", "*none*"
		}
		if r.ZoneAssumed {
			// Marked inline as well as in the source table, because a reader
			// scanning the records will not scroll back.
			local += " ⚠"
		}

		fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n",
			local, utc, r.Level, r.Source, markdownCell(firstLine(r.Text)))
	}

	if hasAssumed(h.Records) {
		b.WriteString("\n⚠ marks a timestamp whose timezone was assumed rather than read from the format.\n")
	}
}

// writeHandoffRaw emits the original lines.
//
// Always included, with no flag to omit them. The receiver may not trust our
// parser, and they are right not to.
func writeHandoffRaw(b *strings.Builder, h session.Handoff) {
	if len(h.Records) == 0 {
		return
	}

	b.WriteString("\n## Raw lines\n\n")
	b.WriteString("Verbatim, in their native formats.\n\n```\n")

	for _, r := range h.Records {
		b.WriteString(r.Raw)
		b.WriteByte('\n')
	}

	b.WriteString("```\n")
}

// writeHandoffZip bundles the markdown, the machine-readable JSON, and the raw
// lines as a separate file for grepping.
func writeHandoffZip(w io.Writer, h session.Handoff) error {
	zw := zip.NewWriter(w)

	markdown, err := zw.Create("extract.md")
	if err != nil {
		return fmt.Errorf("create extract.md: %w", err)
	}
	if err := writeHandoffMarkdown(markdown, h); err != nil {
		return err
	}

	data, err := zw.Create("extract.json")
	if err != nil {
		return fmt.Errorf("create extract.json: %w", err)
	}
	if err := writeHandoffJSON(data, h); err != nil {
		return err
	}

	raw, err := zw.Create("raw.log")
	if err != nil {
		return fmt.Errorf("create raw.log: %w", err)
	}
	for _, r := range h.Records {
		if _, err := io.WriteString(raw, r.Raw+"\n"); err != nil {
			return fmt.Errorf("write raw.log: %w", err)
		}
	}

	if err := zw.Close(); err != nil {
		return fmt.Errorf("close handoff bundle: %w", err)
	}
	return nil
}

// markdownCell escapes what would otherwise break a table row.
func markdownCell(s string) string {
	s = sanitise(s)
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}

func firstLine(s string) string {
	line, rest, found := strings.Cut(s, "\n")
	if !found {
		return line
	}
	// The remainder is in the raw section, so the table says how much is
	// missing rather than silently dropping it.
	return fmt.Sprintf("%s *(+%d lines, see raw)*", line, strings.Count(rest, "\n")+1)
}

func hasAssumed(records []session.HandoffRecord) bool {
	for _, r := range records {
		if r.ZoneAssumed {
			return true
		}
	}
	return false
}

// Commas groups a number into thousands.
//
// Exported because this is the third place that needed it — the handoff, the
// TUI footer, and the pattern listing. A count of records is the number a
// reader most often has to compare at a glance, and 212878 does not compare.
func Commas(n int64) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}

	var b strings.Builder
	lead := len(s) % 3
	if lead > 0 {
		b.WriteString(s[:lead])
	}
	for i := lead; i < len(s); i += 3 {
		if b.Len() > 0 {
			b.WriteByte(',')
		}
		b.WriteString(s[i : i+3])
	}
	return b.String()
}

func humanBytes(n int64) string {
	if n == 0 {
		return "—"
	}
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%dB", n)
	}
	div, exp := int64(unit), 0
	for x := n / unit; x >= unit; x /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f%ciB", float64(n)/float64(div), "KMGTPE"[exp])
}
