#!/usr/bin/env bash
#
# Render the Homebrew formula for a release.
#
#   render-formula.sh <version> <checksums.txt> > loupe.rb
#
# The formula is generated rather than checked in because it has to carry the
# sha256 of four archives that do not exist until the release is built. A
# checked-in formula with placeholder hashes is a formula that is wrong between
# every release and right for about ten minutes after each one.
#
# checksums.txt is the concatenated output of sha256sum, one line per archive:
#
#   <sha256>  loupe_v1.2.3_darwin_arm64.tar.gz
#
# The rendered file belongs in the tap repository, which is separate:
# github.com/VIGIL-OPS/homebrew-tap, at Formula/loupe.rb.

set -euo pipefail

if [ $# -ne 2 ]; then
	echo "usage: $0 <version> <checksums.txt>" >&2
	exit 1
fi

version="$1"
checksums="$2"
bare="${version#v}"
repo="https://github.com/VIGIL-OPS/loupe/releases/download/${version}"

# sha_for <goos> <goarch> — the hash of one archive, or a hard failure.
# Emitting a formula with a missing hash would produce an install error for
# users rather than a build error for us, which is the wrong way round.
sha_for() {
	local want="loupe_${version}_$1_$2.tar.gz"
	local sum
	sum=$(awk -v f="$want" '$2 == f || $2 == "*" f { print $1 }' "$checksums" | head -1)
	if [ -z "$sum" ]; then
		echo "no checksum for $want in $checksums" >&2
		return 1
	fi
	printf '%s' "$sum"
}

# Resolved before the template, not inside it: a failure in $(...) exits only
# the subshell, so a missing hash would otherwise print an error and still
# render a broken formula with exit status 0.
darwin_arm64=$(sha_for darwin arm64)
darwin_amd64=$(sha_for darwin amd64)
linux_arm64=$(sha_for linux arm64)
linux_amd64=$(sha_for linux amd64)

cat <<EOF
# Generated by packaging/homebrew/render-formula.sh — do not edit by hand.
class Loupe < Formula
  desc "Point it at a directory of logs, get a searchable timeline"
  homepage "https://github.com/VIGIL-OPS/loupe"
  version "${bare}"
  license "MIT"

  on_macos do
    on_arm do
      url "${repo}/loupe_${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${repo}/loupe_${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${repo}/loupe_${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${repo}/loupe_${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install "loupe"
  end

  test do
    assert_match "loupe version", shell_output("#{bin}/loupe --version")

    # Reads a directory it has never seen and reports what it found. This
    # exercises parsing, ingest, and the query path rather than only proving
    # the binary starts.
    (testpath/"logs").mkpath
    (testpath/"logs/app.log").write <<~LOG
      {"ts":"2026-08-13T02:11:04Z","level":"error","msg":"read timed out"}
      {"ts":"2026-08-13T02:11:05Z","level":"info","msg":"retrying"}
    LOG
    output = shell_output("#{bin}/loupe #{testpath}/logs 'level:error' --format ndjson")
    assert_match "read timed out", output
    refute_match "retrying", output
  end
end
EOF
